version: "3"
services:
#  kafka:
#    image: 'bitnami/kafka:3.3'
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=127.0.0.1:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    networks:
#      - vdp
  hbase:
    image: 'satoshiyamamoto/hbase:2.1'
    ports:
      - '2181:2181'
      - '60000:60000'
      - '60010:60010'
      - '60020:60020'
      - '60030:60030'
    networks:
      - vdp
networks:
  vdp:
    driver: bridge